### ISSUE TITLE
Esse repositório destruiu o meu wls 2

### ISSUE THREAD

**Issue by fabiocasadossites** [especializati/curso-laravel-11#1]
Depois de clonar o repositório
![Screenshot_490](https://github.com/especializati/curso-laravel-11/assets/44373172/6d6b1618-238b-4946-ab69-8a4b231e76ea)

![Screenshot_489](https://github.com/especializati/curso-laravel-11/assets/44373172/bf1abfab-308c-4981-8c33-3847744f4c18)
 eu entrei na pasta e deu um code . e deu um erro de node e agora se eu tentar entrar em qualquer projeto que eu já tinha o ubuntu deu killer kkkkk

**Comment by carlosfgti** [comment]
Desculpe, o repositório não tem nada haver com isso! :)

Esse código é usado por milhares de usuários, e sem problemas, nunca tive problemas, independente do sistema operacional.
