### ISSUE TITLE
README.md está sem informações mostradas no curso

### ISSUE THREAD

**Issue by GabeHenrique** [especializati/curso-laravel-11#2]
Vim do curso gratuito da plataforma e dentro do README.md não está os dados mostrados no curso.

Fiz questão de criar o arquivo com as etapas mas o esquema de segurança não permite criar pull requests 

[README.md](https://github.com/user-attachments/files/15774794/README.md)

**Comment by carlosfgti** [comment]
Aqui as informações: https://github.com/especializati/setup-docker-laravel/tree/laravel-11-with-php-8.3
